### ISSUE TITLE
UnsupportedOperationException caused by WindowUtils call in TransparentToolTipDialog

### ISSUE THREAD

**Issue by paolofulgoni** [padrig64/ValidationFramework#9]
Running the `FeedbackDemo` I got an `UnsupportedOperationException`.

I'm sorry but I couldn't find a sequence of steps to reproduce the issue. It happened several times while randomly playing with the input controls.
Sometimes, I got the same exception repeatedly thrown in a endless loop. Here below such exception with related stack trace:

```
dic 19, 2014 3:07:38 PM org.jdesktop.core.animation.timing.WrappedRunnable run
GRAVE: (Timing Framework #4) Unexpected UnsupportedOperationException thrown in the timing thread context.
java.lang.UnsupportedOperationException: Set sun.java2d.noddraw=true to enable transparent windows
	at com.sun.jna.platform.WindowUtils$W32WindowUtils.setWindowAlpha(WindowUtils.java:641)
	at com.sun.jna.platform.WindowUtils.setWindowAlpha(WindowUtils.java:1533)
	at com.google.code.validationframework.swing.decoration.support.TransparentToolTipDialog$TransparencyAdapter.timingEvent(TransparentToolTipDialog.java:199)
	at org.jdesktop.core.animation.timing.Animator.timingSourceTick(Animator.java:1340)
	at org.jdesktop.core.animation.timing.TimingSource$1.run(TimingSource.java:225)
	at org.jdesktop.core.animation.timing.WrappedRunnable.run(WrappedRunnable.java:48)
	at org.jdesktop.swing.animation.timing.sources.SwingTimerTimingSource$1.actionPerformed(SwingTimerTimingSource.java:74)
	at javax.swing.Timer.fireActionPerformed(Timer.java:313)
	at javax.swing.Timer$DoPostEvent.run(Timer.java:245)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:744)
	at java.awt.EventQueue.access$400(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:697)
	at java.awt.EventQueue$3.run(EventQueue.java:691)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:714)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

Unfortunately I don't know JNA at all, but I'm afraid this issue is related to my specific JRE or operative system in use.

This is my Java version in use:
```
java version "1.8.0_11"
Java(TM) SE Runtime Environment (build 1.8.0_11-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.11-b03, mixed mode)
```

My operating system is Windows 7 Professional SP1 64bit.

A naive workaround could be to call `WindowUtils.setWindowAlpha(...)` only if `WindowUtils.isWindowAlphaSupported() == true`.

**Comment by paolofulgoni** [comment]
As you suggested, the issue is reproducible by entering a wrong value in the first textfield and then moving the mouse pointer over the tooltip.

I checked `WindowUtils.isWindowAlphaSupported()` before executing the line causing the exception and the returned value is `false`. So in my specific case that check would be enough.

If you agree, I can propose a pull request to fix this issue.

**Comment by padrig64** [comment]
That would be nice. Thank you.

**Comment by padrig64** [comment]
Hi Paolo,

Since I needed to release the framework for other changes and additions, I took the opportunity to clean up the FeedbackDemo and add the fix you suggested in the TransparentToolTipDialog.
The changes are now in the release 3.3.2.
Please let me know if it works for you.
Thanks for your input.

**Comment by paolofulgoni** [comment]
Sorry for not providing the fix.

I tested the latest version and I didn't get the exception anymore!
Thank you!

I must say that my JDK version in use now is different (8u40-ea) but I think it doesn't make any difference. From my point of view, you can consider the issue fixed.

**Comment by padrig64** [comment]
No problem for the fix ;) That was the opportunity to clean-up some example code (more to come...)
Thanks for checking anyway! I will close the issue.
